### ISSUE TITLE
drmr_ui.xml missing

### ISSUE THREAD

**Issue by Joeboy** [nicklan/drmr#1]
```
joe@Joyce:~/building/drmr$ make
make: *** No rule to make target `drmr_ui.xml', needed by `drmr.lv2'. Stop.
```

**Comment by nicklan** [comment]
Crap, sorry about that, left-over dep in the makefile.

You can re-pull it and it should work now, or just remove any reference 
to it in the Makefile

**Comment by Joeboy** [comment]
Cool, it builds and runs in jalv now. Will check it out in more depth when I'm not at work.

**Comment by nicklan** [comment]
Cool, hope the rest of it works well :)
