### ISSUE TITLE
wishlist: 

### ISSUE THREAD

**Issue by ghost** [nicklan/drmr#4]
At the beginning - thanks for this plugin. It will be a great thing.

I use / test it and I have some thoughts.

Triggers
Currently you can only change the "base midi note". I propose to create an array of triggers.

At the moment it looks like this:
nn = data[1];
nn-=baseNote;
trigger_sample(drmr,nn,data);

I propose to replace:
nn = trigger_table[data[1]];
if(nn>0){
  nn--;
  trigger_sample(drmr,nn,data);
}
/ / Samples in trigger_table numbers are increased by 1

"Sample a zero position" in this case would be unnecessary.
Table trigger_table for a each kit should be remembered (saved to a file).

Graphically this would look like a matrix: rows - midi notes (C2, C#2, D2...) , columns - sample number (or names).

Indicators play sample.
The topic has been exhausted in previous posts, so I will not be repeated.

And a little thing - to reduce the size of the wheel from 50 to 25 (or similar). But this is only my whim. ;)

I'm currently using Hydrogen and Ardour. This plugin is a positive revolution! 
Very fan of you. With great interest I will be looking at further development DrMr.

Regards :)
Marcin.

**Comment by nicklan** [comment]
Thanks for the feedback!  Always nice to know people are actually using DrMr.

As far as your suggestions:

trigger_table: 
I'm not 100% sure what you want to accomplish with this.  The only real use-case I can think of is to re-map what sample a particular note plays.  I think is is probably better accomplished with being able to edit the loaded kit and select what sample goes in each slot.   This is the next big feature on my list, so DrMr should be able to do sample loading into individual slots as soon as I find a chunk of free time.  If you have another use-case in mind that isn't addressed by that feature but is by the trigger table, please do let me know.

Indicators:
I assume you saw in the other topic that the lv2unstable branch has indicators.  At this point I'm just waiting for a couple of hosts to have stable lv2-1.0 support (Ardour 3 svn already does, so the final release also will)  and I'll merge and have the master branch of DrMr with all those new features.

Knob Size:
Yeah, this is a good suggestion.  I need to come up with a good way to control knob size (maybe tied to window size, or maybe an option), but I'll add it sometime soon. 

Thanks, and please let me know if you find any bugs or have other suggestions!

Knob

**Comment by ghost** [comment]
I speak English poorly - so forgive the lack of precision.

The main idea trigger_table (or trigger_matrix) is the ability to quickly change the "kit" and the ability to play standard MIDI tracks.

For example: I create all the percussion using GMkit, but later turns out that the song sounds better with a set of UltraAcousticKit (or other). It would be nice to be able to quickly swap kits without having to edit the path.

Hydrogen Drumkits have no standard as to where what you want to have a sample (eg = sample_0 kick, snare = sample_1 etc.). So it is not possible to quickly change the set of samples at the stage of mixing the song.

If DrMr have an array / matrix, which would allow the matching order of samples in a set for my needs - I'd be delighted. :)

If I understand what you wrote, it is your idea of slots is in line with my proposal. The difference is probably only a few small things. :)

Indicators are excellent. Although I have seen them only on the screenshots (I'm using AVLinux with gtk+ 2.20.0 only), but this is it!

The plug is going to be very interesting and I would definitely use it.
Once again, good luck and congratulations to the idea and implementation.

**Comment by nicklan** [comment]
Don't worry about your English, it's perfectly fine.  

To your points (I'll do them in reverse order):

Hydrogen not having a standard for kick/snare/etc:
Yes, this is annoying, and ultimately and problem with the available Hydrogen kits.  It's a shame there's not a more enforced standard.  Regardless, the effort in re-mapping everything for a new kit, plus the complexity of the UI make me very hesitant to want to add this feature.  You would be better off simply editing the hydrogen kit (in Hydrogen or just bust open the XML) and creating a new kit with the samples where you want them.  I imagine this would be very close to the same amount of work, and doesn't introduce a whole load of complexity into DrMr.  

Furthermore, this mapping would be kit specific, so you'd end up wanting some way of tying a particular map to a kit, and I don't even want to think about managing that complexity :)  

All in all, the amount of work to move around samples in a kit seems to solve this in a much more understandable way.  But what you have made me realize is the the UI for selecting a sample would benefit from having shortcuts to the samples from the loaded kit, so you could quickly say, make sample 2 the sample that's currently at sample 8.

I don't see at all how the trigger matrix maps to quickly switching between kits.  Either way you're going to have to select the kit in the drop-down, and if you need to edit a complex re-mapping table, that's going to take probably more time.  Better to just align the samples of the kits you might like and then you're set forever.

The GTK version you have isn't the problem, the only issue is host support for the new LV2 features that are required to support the indicators (there is no way to notify the UI that a midi note has been received in the core in the old spec).  I would hope AVLinux will support Ardour 3 when it comes out, in which case you'll get all the nice new stuff them.

**Comment by ghost** [comment]
Thank you for your extensive explanation and patience.

I believe that you have a lot better than I thought. I am glad that some way will be possible to set samples. How will it be done - it's a secondary matter. :)

Therefore I am looking forward to a stable version of DrMr and... gtk+ 2.22 in AVLinux ;)

Regards
Marcin.
